# Generated by Django 2.2.2 on 2019-07-28 12:15

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=200)),
                ('last_name', models.CharField(blank=True, default='', max_length=200)),
                ('profile_picture', models.ImageField(blank=True, upload_to='')),
                ('authorised', models.BooleanField(default=False)),
                ('specialisation', models.CharField(blank=True, default='', max_length=100)),
                ('birth_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('joined_on', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, default='')),
                ('skills', django.contrib.postgres.fields.jsonb.JSONField(default=main.json.skills)),
                ('education', django.contrib.postgres.fields.jsonb.JSONField(default=main.json.education)),
                ('links', django.contrib.postgres.fields.jsonb.JSONField(default=main.json.links)),
                ('contact', django.contrib.postgres.fields.jsonb.JSONField(default=main.json.contact)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
