# Generated by Django 2.2.2 on 2019-08-10 20:28

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default='UserName', max_length=200)),
                ('first_name', models.CharField(blank=True, default='', max_length=200)),
                ('last_name', models.CharField(blank=True, default='', max_length=200)),
                ('profile_picture', models.CharField(blank=True, default='', max_length=300)),
                ('authorised', models.BooleanField(default=False)),
                ('specialisation', models.CharField(blank=True, default='', max_length=100)),
                ('birth_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('joined_on', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, default='')),
                ('designation', models.CharField(blank=True, default='Core Member', max_length=100)),
                ('skills', django.contrib.postgres.fields.jsonb.JSONField(default=main.json.skills)),
                ('college', models.TextField(blank=True, default='', null=True)),
                ('degree', models.TextField(blank=True, default='', null=True)),
                ('passing_year', models.IntegerField(blank=True, default=0, null=True)),
                ('links', django.contrib.postgres.fields.jsonb.JSONField(default=main.json.links)),
                ('contact', django.contrib.postgres.fields.jsonb.JSONField(default=main.json.contact)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('event_pic', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('time', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('location_link', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('registration_link', models.CharField(blank=True, default='', max_length=400, null=True)),
            ],
        ),
    ]
