# Generated by Django 2.2.2 on 2019-07-28 12:23

from django.db import migrations
import django.contrib.postgres.fields
import main.json


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='contact',
            field=django.contrib.postgres.fields.JSONField(default=main.json.contact),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='education',
            field=django.contrib.postgres.fields.JSONField(default=main.json.education),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='links',
            field=django.contrib.postgres.fields.JSONField(default=main.json.links),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='skills',
            field=django.contrib.postgres.fields.JSONField(default=main.json.skills),
        ),
    ]
