# Generated by Django 2.2.2 on 2019-07-28 12:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import main.json


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190728_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='contact',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=main.json.contact),
        ),
        # migrations.AlterField(
        #     model_name='teammember',
        #     name='education',
        #     field=django.contrib.postgres.fields.jsonb.JSONField(default=main.json.education),
        # ),
        migrations.AlterField(
            model_name='teammember',
            name='links',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=main.json.links),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='skills',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=main.json.skills),
        ),
    ]
