# Generated by Django 2.2.2 on 2019-07-28 12:47

from django.db import migrations
import django.contrib.postgres.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190728_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='contact',
            field=django.contrib.postgres.fields.JSONField(default={'address': '', 'email': '', 'phone': ''}),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='education',
            field=django.contrib.postgres.fields.JSONField(default={'education': ['Education1', 'Education2']}),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='links',
            field=django.contrib.postgres.fields.JSONField(default={'facebook': 'https://www.facebook.com/', 'github': 'https://github.com/', 'twitter': 'https://twitter.com'}),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='skills',
            field=django.contrib.postgres.fields.JSONField(default={'skill': ['skill1', 'skill2']}),
        ),
    ]
