# Generated by Django 2.2.2 on 2019-07-28 13:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190728_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='contact',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'address': '', 'email': '', 'phone': ''}),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='education',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'education': ['Education1', 'Education2']}),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='links',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'facebook': 'https://www.facebook.com/', 'github': 'https://github.com/', 'twitter': 'https://twitter.com'}),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='skills',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'skill': ['skill1', 'skill2']}),
        ),
    ]
