# Generated by Django 2.2.2 on 2019-07-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190728_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='contact',
            field=models.TextField(blank=True, default={'address': '', 'email': '', 'phone': ''}),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='education',
            field=models.TextField(blank=True, default={'education': ['Education1', 'Education2']}),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='links',
            field=models.TextField(blank=True, default={'facebook': 'https://www.facebook.com/', 'github': 'https://github.com/', 'twitter': 'https://twitter.com'}),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='skills',
            field=models.TextField(blank=True, default={'skill': ['skill1', 'skill2']}),
        ),
    ]
