# Generated by Django 2.2.2 on 2019-07-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190728_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='contact',
            field=models.TextField(blank=True, default='{"phone": "", "address": "", "email": ""}'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='education',
            field=models.TextField(blank=True, default='{"education": ["Education1", "Education2"]}'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='links',
            field=models.TextField(blank=True, default='{"facebook": "https://www.facebook.com/", "twitter": "https://twitter.com", "github": "https://github.com/"}'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='skills',
            field=models.TextField(blank=True, default='{"skill": ["skill1", "skill2"]}'),
        ),
    ]
