# Generated by Django 2.2.2 on 2019-07-30 20:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190731_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='contact',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'address': 'p', 'email': 'p', 'phone': 'p'}),
        ),
    ]
