# Generated by Django 2.2.2 on 2019-08-03 17:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190731_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='contact',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'address': 'p', 'email': 'p', 'phone': 'p'}),
        ),
        # migrations.AlterField(
        #     model_name='teammember',
        #     name='education',
        #     field=django.contrib.postgres.fields.jsonb.JSONField(default={'education': ['Education1', 'Education2']}),
        # ),
        migrations.AlterField(
            model_name='teammember',
            name='links',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'facebook': 'https://www.facebook.com/', 'github': 'https://github.com/', 'twitter': 'https://twitter.com'}),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='skills',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'skill': ['skill1', 'skill2']}),
        ),
    ]
