# Generated by Django 2.2.2 on 2019-08-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190803_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
