# Generated by Django 2.2.2 on 2019-08-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190804_2102'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='teammember',
        #     name='education',
        # ),
        # migrations.AddField(
        #     model_name='teammember',
        #     name='college',
        #     field=models.TextField(blank=True, default=''),
        # ),
        # migrations.AddField(
        #     model_name='teammember',
        #     name='degree',
        #     field=models.TextField(blank=True, default=''),
        # ),
        # migrations.AddField(
        #     model_name='teammember',
        #     name='passing_year',
        #     field=models.IntegerField(blank=True, default=''),
        # ),
    ]
