# Generated by Django 2.2.2 on 2019-08-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190811_0120'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='teammember',
        #     name='college',
        #     field=models.TextField(blank=True, default='', null=True),
        # ),
        # migrations.AlterField(
        #     model_name='teammember',
        #     name='degree',
        #     field=models.TextField(blank=True, default='', null=True),
        # ),
        # migrations.AlterField(
        #     model_name='teammember',
        #     name='passing_year',
        #     field=models.IntegerField(blank=True, default='', null=True),
        # ),
    ]
