# Generated by Django 2.2.2 on 2019-08-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190811_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='username',
        ),
    ]
