# Generated by Django 2.2.2 on 2019-08-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20190812_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='passing_year',
            field=models.IntegerField(blank=True, default=2000, null=True),
        ),
    ]
