# Generated by Django 2.2.2 on 2019-08-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20190812_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
