# Generated by Django 2.2.2 on 2019-08-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20190816_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
