# Generated by Django 2.2.2 on 2019-08-16 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20190816_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='id',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
