# Generated by Django 2.2.2 on 2019-08-30 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_teammember_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('event_pic', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('time', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('location_link', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('registration_link', models.CharField(blank=True, default='', max_length=400, null=True)),
            ],
        ),
    ]
