# Generated by Django 2.2.2 on 2019-09-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='upcomming',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
