# Generated by Django 2.2.2 on 2019-11-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_hackgtbit_serial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='upcomming',
            new_name='upcoming',
        ),
        migrations.AlterField(
            model_name='hackgtbit',
            name='date',
            field=models.DateField(blank=True, default='2020-01-18', null=True),
        ),
        migrations.AlterField(
            model_name='hackgtbit',
            name='time',
            field=models.TimeField(blank=True, default='12:00:00', null=True),
        ),
    ]
